users:
  - name: lyasspiehler
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUjpRGqqXd4z1tGR1fXVyk86n8RGpCzGs75OQBdKDK4TsMus7faoaBZtoWK86j9PPcVWPegGq31ftWXtONj8AqrtsBaN/Qn/jpYiYMXTkixTp09aXDZlSS/NCwYPIxybnj8npVua73BGQH5u34PpZXSB07ioTgKOC87Tas48iOKQArHuPpCmancAV7qWDkv51ALOijQZjydPHr/TPSzq4yXg3q+KD52DXoiusLShAHqmzmtQjNmW3FFxBAzrEP7yJfKctiRZpb7qm0wgvaS4E+XSyredwUbAuZr0O23OLGFTUupuuw2YQNBGJUEp1WgD+LRizTyW+sb3DUVivNS5GtYlbOHImfj0B/ecx9ztJreNR1N+e8jCpAGuDv0nbDD7I6rU5vKuK2IRorUKbVZuah8CRn6wmhRKsPNfYBGPSkInwcU7AebxF10ROzBQcf6bdSCXWhAHFAvKxWDq0jJJvnabsn9VSLd4AEOMLoOrNWPKm4lGsNndEXIdMSaQH/vyM= EPC-lyasAWSKP-C
  - name: taylorwegener
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRYME99FAZMwH4yOvDZ/l1EF21HAsILZFH9BxlP2rwqo2IBjh1oX/10JPzcKzy9tK8gTkyhSpuSpKs65lJj/77Cn81JsD/u01TphakePMu0a8JQsw7ymhXj+QGdBB7x6ZHUM+oj6HZElf5W2CykuG4cbKoEcA6JnqCPBN/TdBvgrUKekpio165H8d3yvrQPEmqXU90qf4M4zJowAtGB5nTSil9oKS8+5i3WjO3wCq52BpTEx0pU6352Jw9Ksm7rpnDGaNe/kgYppBWTTqD8L027UHN4anvbG01PCoXy7OVpSvCZrb9NRT+xHvfVwKjrdmaOA+MYGqsyUjNjgrKfdzqfY9rqobXJRwHQDHFlujmJe9BUJBxQU4gKRuQZZsB3M7B19jWKiCfKEMX+GNzQjvTZzLk5Q3N9a7L1rzQRs4iQlOOXCrcX5EkNijHbFMeujBFdNxT8nzMNs8OwVFjVKfhuW+WonW/uqugA1Z35/m7CyUpEI4/O9jliMfsuFf+ofc= azuread\taylorwegener@SHLT-0Y1P
  - name: giannirubio
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHj7JSm/ZSD7WwjnUAg1o1l4cJU61OhhhkM38tx5lfV5FSCBMdx7GyxrwWd0FmZwVlpn26p7OZlSLRtvGuo639cixe4UGnn5TI8gDB6Fm6SNictuL+WtHegqoE7Um0ZU95pEl5U9eEvrvpQdh0UZGj/u1S4XrLO7kZk2iDDFAJrL5RFvxsCsL+zHaDHch6Q8APf60ZCLVDr0dwO5ZiXzdgaEMocTFarCGp2Y82o8iwXpNMW/aXDgR1SJDIv2c8oPhZXa+mX0F8KZQ2m7DYVYxhIj9q+KoNxpntYkv1nhkyY0aWUEA/3Qb4H2XtuxzmrDuKCMBY8t4YjKRjNMQ6zrjDmiCsakKAtUSVgJKk9qrGUr3OFqpGOvX66xlXzeu8RuAUSmsu5aPXazaFymrxc/8dEWJARANNO7USVir2jVL8UFlpcxEJPC5pG8SXeRpaS+Lw3YdiFdf690N1UpcuUsUAMaY1+l1UhhbWH9zGSwYl7klMCTu2Y8qbHjBmSIgXd2c= azuread\giannirubio@SH-4306
  - name: tylerjordan
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvjEOXFf2iSvsndFrAm6pNxrB1Dzwg/IFGDj0WraYmS9a+z5fphH+VtNguS301L05mKZpIg8RmHZnMLBEyAjRPTdlIQHzTMjvspPtYpyaamWFMWQTL2B6f10f2W5tEY6Tc7A4TludR517lY3jFNSU/dQ1ZV/dHTHWyZx0MnWiNb165Y5pMd4MYfORX6JAolQUWMttqFejHVRT6hSAlAzJUAQMJtvIv1sFxrUELpGzBmWAuxzRO8z4UA1awRsgr7foadaYIU2odDkSqsPP+mQHe4/ejHDxH5I12ePUa0aBA5FidKYIQFCdcs/XH3A1O87RBEczuMObSy6sCmGDhoUZqX/w3r+89hm2Exbmtgdyzn8ReCtHK/nv4i4c2s37nG7lpMDayI7feYvjeKG0xEQsmsWnkWKurPT+6FibDnRAiLmFO03gsrlQTiJ22IQqDBhX395dU9i/9ef3k/hqltT3/PV9aiZNYrQnb8crOnXiHuVcoWleHfOIX+1F/o/4X8sU= azuread\tylerjordan@Sapphy
  - name: kristomaine
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDKvkJO6Q7iSM9X7gondTJN2h25rl/Y0lFTZjpDT/wUB tomainek92@gmail.com
  - name: chadaiena
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDt09jKwMF+DzkRKfYsCBfWJBV3/vAbR+/NKFyPrkpVHo76QBp8CUH7K4XaPB6nMlt8cssggbsX9FINK5lMu+In8tnZxqY4ROntp+bKaH07R9jZmsb6TjThaKi0qM8XzGiO+Sc1RyHXu22sVgIgogsh4p4g20A1qxdLrIIgaU/VPcMN+OJMVhRvHz8RK/u+J0BQt3jkzJ1t1y4F1U6b/mB7F3LE6Ms5RobWQZa3qfhs706JbJ/KeFv3Wdf9IaTcla6hJVh0KzvITRpSgnVziLkNz/4MceqZWHvyBkFyOxbMaHNbVAt0+G3HvdTLjikDK+3g4UX9E5k0XhB60AQIij9Qj5Lh2dC5aaLXo0L8BUwP6Cl/24/yMXn+1S2P2yxvHmnZIkOscJFRDYudqrlDlC/6s2HjfbYM/EF+BsFv0GtMhBGhSKfGwh5TCsMW4EliIfkmkCpUZ8G9arFlPUno9QhI0KwMKA0wbLr+4V8Nw/dtxBaHBhNcFa/Bk1key/LwR88= azuread\chadaiena@SH-4474
  - name: andresrealpozo
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJZX+fLW+YiH1o9iVFddfAqkFYkkkMKFO5/YHzxLnWcu azuread\andresrealpozo@DESKTOP-FRTT9VQ
  - name: jeffkarle
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGNVWA1Cuz4v0ZBQ9J0A/85FNMknuZNBQ+GmZ5KbzNYO azuread\jeffkarle@SHLT-4332
  - name: joselopez
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJj8qevdlEm8bNWhbbHZtAVPwxCdq0cAJL/lBMfgPYTO AzureAD+JoseLopez@SH-4304
  - name: kimberlytodaro
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxL5FgLgYBIm8AVdS1RXF46RaNq/vE0dMCLkUPxQjN1jIZP8SKhvLwWYcUOMJWlYqQN06LBapjsyXf4qz/1IH3mo8su3K4H7puM7kTERM0fX5dYMMJmO7+UFDc3YAKLVa777h5rACijtN6L6rrQEAdVIfq1RkeFMSMN5abUjUiS/i7qZdnJSzysvVVox8b3kkrMWzTQypIZhKU3pq42cSQ8joi2Sol6kWMNuZ7aLlkPdMf8a5WD/ocnQqyu8K4OgDVRhadIHui0wxro7bVK4VdX/H20tvM6wrCdMxETeWYKsZQIHTAWcro1EeP/ey7ITZ9NaRgwNOJmwjlV9ma0x+UO8DqU20b2KF9TSsfguoFpOJLww9g3l6enm8rt2Hz92PFRxV2GzhauzX5j6ZM+I3IaTRgPLIuipGGe86Vjh/33mn1iqQCXip5MXMFZxa9p+eKtFakamSuHcMOfNfp8q/nCs8MA5yWKcnA8ZG7+5EdD1t1mnC/0GW3SGV+axwonbM= kimbe@kit-desktop
  - name: willstrayer
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICubLg9sLW2392Ec1NKtRkigd/IHCAv2lj60XyK+lXrC azuread\willstrayer@SH-4040
  - name: kristomaine
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDKvkJO6Q7iSM9X7gondTJN2h25rl/Y0lFTZjpDT/wUB tomainek92@gmail.com
  - name: christopherlamb
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDupSKJoHeicTdlqYkNprhA2YT/+eqxZ3lXS4GNaPBXT azuread\christopherlamb@SH-4035 ssh-ed25519
  - name: aprilchien
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHrgOYUn33guVHwDF9xcjp8Ue+dLbXNJk0LZThF2RzeC azuread\aprilchien@SH-4029
  - name: alisheikh
    # groups: [sudo]
    append: true
    shell: /bin/bash
    create_home: true
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuLrFlaZhS1LLkhSlv+uwjzVBpULsOHRC38gsgaND36Yyrq5LFUcj6n/VU3D17D3U1jYkpNb0m/Jk4EuggpOeheQgl/3jWVU/pjaQkylTBgyRAra+aqFRzMAveAAEa5wOo5i+zgme0faFSNdZjrBAt72iZWHV2gRTXQaI/5+xWrZfSjKhW2q9IQR2ISIFk7J/2bIEsBExaWyPmZwDdFLX4Nx5iYifMEE2/TLLsxUZxf8D2rCCpTFK74f8MskcBuqTDTVLxgMcLvJlQl+/3hAtKk2J+iEkZ/FvTDfNWZylhvLgywSR4ta+eda1VJcH8vFoFWomYP5OAE5P9kJdZZaPNuID4IQ4AWY1WvvQpv4GIjp6J+u5x6iTstQokWRTaUDG6hQ25uBUgDa40pfciG5kljrBBm4GZmhrL0rXsE84pf6RF+BrM55lTf0amBGQCewyvRPoX8QoS36blE8VaHXTVkfH33w5nCPyr/8EGKOZeE/QD8BRUvbHrDqIWw02Ok9Z+9XsDmY6xtJ9kMPQcBEvPsRIdx0pbVWXjGiyTj2MI0guesi3XZ2IcQdsqyoirpb/Ijl2BjoZMT/0TtfOQMLB7piURyRlzKekbn3lCp7OpJStLz/xO8Qpyhf3HgxsezacVmKSh9ftoSdZJ85QUjLEhnfZfwf3rmRpr54Rwh4baXQ== asheikh@Ali-MacBook-Pro-14.local
