user_sqlengine: sapphire\admin
user_sqlagent: sapphire\admin
caboodle_user_warehouse: sapphire\admin
clarity_user_console: sapphire\admin
clarity_user_datalink: sapphire\admin
caboodle_user_execution_service: sapphire\admin
caboodle_install_user: sapphire\admin
slicerdicer_user: sapphire\admin


volumes:
  clarsql00:
    DriveLetter: S
    FSLabel: Clarity_SQL
  clarmount00:
    DriveLetter: M
    AllocationUnitSize: 65536
    FSLabel: null
  clarrpt00:
    AccessPath: M:\Clarity_Report1
    FSLabel: Clarity_Report1
    AllocationUnitSize: 65536
  clarrpt01:
    AccessPath: M:\Clarity_Report2
    FSLabel: Clarity_Report2
    AllocationUnitSize: 65536
  clarrpt02:
    AccessPath: M:\Clarity_Report3
    FSLabel: Clarity_Report3
    AllocationUnitSize: 65536
  clarrpt03:
    AccessPath: M:\Clarity_Report4
    FSLabel: Clarity_Report4
    AllocationUnitSize: 65536
  clarrpt04:
    AccessPath: M:\Clarity_Report5
    FSLabel: Clarity_Report5
    AllocationUnitSize: 65536
  clarrpt05:
    AccessPath: M:\Clarity_Report6
    FSLabel: Clarity_Report6
    AllocationUnitSize: 65536
  clarrpt06:
    AccessPath: M:\Clarity_Report7
    FSLabel: Clarity_Report7
    AllocationUnitSize: 65536
  clarrpt07:
    AccessPath: M:\Clarity_Report8
    FSLabel: Clarity_Report8
    AllocationUnitSize: 65536
  clarlog00:
    AccessPath: M:\Clarity_ReportLog
    FSLabel: Clarity_ReportLog
    AllocationUnitSize: 65536
  clarstg00:
    AccessPath: M:\Clarity_Stage1
    FSLabel: Clarity_Stage1
    AllocationUnitSize: 65536
  clarstg01:
    AccessPath: M:\Clarity_Stage2
    FSLabel: Clarity_Stage2
    AllocationUnitSize: 65536
  clarlog01:
    AccessPath: M:\Clarity_StageLog
    FSLabel: Clarity_StageLog
    AllocationUnitSize: 65536
  claraudit00:
    DriveLetter: F
    FSLabel: Clarity_Audit
    AllocationUnitSize: 65536

sql_install_source_dir: files
sql_install_iso: SQLServer2022-x64-ENU-Dev.iso
# dsc_sqltempdbdir: 'S:\SQL\SQLData'
# dsc_sqltempdblogdir: 'S:\SQL\SQLData'
dsc_installsqldatadir: 'S:\SQL\SQLinstall'
dsc_instancename: MSSQLSERVER
dsc_sqlbackupdir: 'S:\SQL\'
dsc_sqluserdbdir: 'S:\SQL\SQLData'
dsc_sqluserdblogdir: 'S:\SQL\SQLLogs'
dsc_sqlsysadminaccounts: # The SQL setup requires at least one system administrator account
  - sapphire\admin
  # - .\ssm-user
# dsc_features: SQL
smss_install_source_dir: https://download.microsoft.com/download/9/b/e/9bee9f00-2ee2-429a-9462-c9bc1ce14c28
smss_install_file: SSMS-Setup-ENU.exe
ssms_product_id: "{98566bce-3110-4bc9-b372-a014a6eb5b58}"
# sql_sa_password: # can be defined as env var SQL_SA_PASSWORD=''
dsc_agtsvcaccount: sapphire\admin
dsc_sqlsvcaccount: sapphire\admin

# use these for clarity
Traceflags:
  - 2467 
  - 4139 
  - 8086 
  - 8121 
  - 12502

# use these for caboodle
#Traceflags:
#  - 2467 
#  - 4139 
#  - 8086 
#  - 8121 
#  - 12502
#  - 11064
#  - 11068
#  - 11631
#  - 11634

# Create Databases. use unique variables so we don't overlap with microsoft_sql db creation (it uses sql_databases)
# db_size, db_max_size, and db_growth are per file
sql_dbs:
  - name: 'Clarity_Report'
    db_size: 1024MB
    db_max_size: 4096MB
    db_growth: 256MB
    log_size: 512MB
    log_max_size: 2048MB
    log_growth: 128MB
    recovery_model: 'SIMPLE'
    log_path: 'M:\Clarity_ReportLog'
    data_path: 'M:\Clarity_Report'
    data_file_count: 8
    filename: CLRpt
  - name: 'Clarity_Stage'
    db_size: 1024MB
    db_max_size: 4096MB
    db_growth: 256MB
    log_size: 512MB
    log_max_size: 2048MB
    log_growth: 128MB
    recovery_model: 'SIMPLE'
    log_path: 'M:\Clarity_StageLog'
    data_path: 'M:\Clarity_Stage'
    data_file_count: 2
    filename: CLStg
#  - name: 'Caboodle_Report'
#    db_size: 1024MB
#    db_max_size: 4096MB
#    db_growth: 256MB
#    log_size: 512MB
#    log_max_size: 2048MB
#    log_growth: 128MB
#    recovery_model: 'SIMPLE'
#    log_path: M:\Warehouse_ReportLog
#    data_path: M:\Warehouse_Report
#    data_file_count: 8
#    filename: CDWRpt
#  - name: 'Caboodle_Stage'
#    db_size: 1024MB
#    db_max_size: 4096MB
#    db_growth: 256MB
#    log_size: 512MB
#    log_max_size: 2048MB
#    log_growth: 128MB
#    recovery_model: 'SIMPLE'
#    log_path: M:\Warehouse_StageLog
#    data_path: M:\Warehouse_Stage
#    data_file_count: 4
#    filename: CDWStg
#  - name: 'SlicerDicer'
#    db_size: 512MB
#    db_max_size: 1024MB
#    db_growth: 64MB
#    log_size: 256MB
#    log_max_size: 512MB
#    log_growth: 32MB
#    recovery_model: 'FULL'
#    log_path: M:\SlicerDicer
#    data_path: M:\SlicerDicer
#    data_file_count: 4
#    filename: SlicerDicer